// Autogenerated by geninfo, do not edit

package gcewing.architecture;

public class Info {
	static final String modName = "ArchitectureCraft";
	static final String modID = "architecturecraft";
	//static final String modPackage = "";
	static final String versionNumber = "1.8.0";
	static final String versionBounds = "[1.11.2)";
	static final String acceptedMinecraftVersions = "[1.11.2]";
}
